version: '3.8'

services:
  ms-event:
    build:
      context: ms-event
      dockerfile: Dockerfile
    container_name: ms-event
    restart: always
    ports:
      - 8080:8080
    networks:
      - ms_network

  ms-ticket:
    build:
      context: ms-ticket
      dockerfile: Dockerfile
    container_name: ms-ticket
    restart: always
    ports:
      - 8081:8081 
    environment:
      - MSEVENT_URL=http://ms-event:8080
    networks:
      - ms_network

networks:
  ms_network:
    driver: bridge

