spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  application:
    name: ms-ticket
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.wokh8.mongodb.net/db_ticket?retryWrites=true&w=majority&appName=Cluster0
  rabbitmq:
    addresses: amqps://cxcgepkp:seSpZhMmFsuG7rXgcdr_633eXXw3xoqZ@beaver.rmq.cloudamqp.com/cxcgepkp
broker:
  queue:
    email:
      name: default.email
server:
  port: 8081
